(setq user-init-file "@ADEMACS_INIT_FILE@")
(setq user-emacs-directory "@EMACS_DIR@")
(setq default-directory "@HOME_DIR@/Git/ademacs/ademacs.d")
(defvar ade/fonts-install-dir "@FONTS_INSTALL_DIR@")
(load user-init-file)
